import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../core/api_client.dart';
import '../core/app_exception.dart';
import '../models/user.dart';

final authServiceProvider = Provider<AuthService>((ref) {
  return AuthService(ref.read(dioProvider));
});

typedef LoginResult = ({String accessToken, String refreshToken, User user});
typedef RefreshResult = ({String accessToken, String? refreshToken});

class AuthService {
  AuthService(this._dio);
  final Dio _dio;

  Future<LoginResult> login(String email, String password) async {
    try {
      final res = await _dio
          .post('/auth/login', data: {'email': email, 'password': password});
      final data = res.data as Map<String, dynamic>;
      final accessToken = data['accessToken'] as String?;
      final refreshToken = data['refreshToken'] as String?;
      final userMap = data['user'] as Map<String, dynamic>?;
      if (accessToken == null || refreshToken == null || userMap == null) {
        throw const ApiException(0, 'Unexpected server response');
      }
      return (
        accessToken: accessToken,
        refreshToken: refreshToken,
        user: User.fromJson(userMap),
      );
    } on DioException catch (e) {
      throw _map(e);
    }
  }

  Future<User> register(String email, String password, String fullName) async {
    try {
      final res = await _dio.post('/auth/register',
          data: {'email': email, 'password': password, 'full_name': fullName});
      return User.fromJson(res.data as Map<String, dynamic>);
    } on DioException catch (e) {
      throw _map(e);
    }
  }

  Future<RefreshResult> refresh(String refreshToken) async {
    try {
      final res = await _dio
          .post('/auth/refresh', data: {'refreshToken': refreshToken});
      final data = res.data as Map<String, dynamic>;
      final accessToken = data['accessToken'] as String?;
      if (accessToken == null) {
        throw const ApiException(0, 'Unexpected server response');
      }
      return (
        accessToken: accessToken,
        refreshToken: data['refreshToken'] as String?,
      );
    } on DioException catch (e) {
      throw _map(e);
    }
  }

  Future<void> logout() async {
    try {
      await _dio.post('/auth/logout');
    } on DioException {
      // Ignore logout errors — clear local state regardless
    }
  }

  AppException _map(DioException e) {
    if (e.error is AppException) {
      return e.error as AppException;
    }
    final status = e.response?.statusCode;
    // Use the server's error message if present (e.g. "Invalid credentials" on 401).
    // Only fall back to AuthException when there is no body — that means it was a
    // token-expiry 401 generated by the interceptor with no response body.
    final msg = e.response?.data?['error'] as String?;
    if (msg != null) return ApiException(status ?? 0, msg);
    if (status == 401) return const AuthException();
    return ApiException(status ?? 0, 'Unknown error');
  }
}
