import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../core/api_client.dart';
import '../core/app_exception.dart';
import '../models/user.dart';

final authServiceProvider = Provider<AuthService>((ref) {
  return AuthService(ref.read(dioProvider));
});

typedef LoginResult = ({String accessToken, String refreshToken, User user});
typedef RefreshResult = ({String accessToken, String? refreshToken});

class AuthService {
  AuthService(this._dio);
  final Dio _dio;

  Map<String, dynamic> _bodyAsMap(Object? data) {
    if (data is Map) return Map<String, dynamic>.from(data);
    throw const ApiException(0, 'Unexpected server response');
  }

  Future<LoginResult> login(String email, String password) async {
    try {
      final res = await _dio
          .post('/auth/login', data: {'email': email, 'password': password});
      final data = _bodyAsMap(res.data);
      final accessToken = data['accessToken'] as String?;
      final refreshToken = data['refreshToken'] as String?;
      final userMap = data['user'] is Map
          ? Map<String, dynamic>.from(data['user'] as Map)
          : null;
      if (accessToken == null || refreshToken == null || userMap == null) {
        throw const ApiException(0, 'Unexpected server response');
      }
      return (
        accessToken: accessToken,
        refreshToken: refreshToken,
        user: User.fromJson(userMap),
      );
    } on DioException catch (e) {
      throw _map(e);
    }
  }

  Future<User> register(String email, String password, String fullName) async {
    try {
      final res = await _dio.post('/auth/register',
          data: {'email': email, 'password': password, 'full_name': fullName});
      return User.fromJson(_bodyAsMap(res.data));
    } on DioException catch (e) {
      throw _map(e);
    }
  }

  Future<RefreshResult> refresh(String refreshToken) async {
    try {
      final res = await _dio
          .post('/auth/refresh', data: {'refreshToken': refreshToken});
      final data = _bodyAsMap(res.data);
      final accessToken = data['accessToken'] as String?;
      if (accessToken == null) {
        throw const ApiException(0, 'Unexpected server response');
      }
      return (
        accessToken: accessToken,
        refreshToken: data['refreshToken'] is String
            ? data['refreshToken'] as String
            : null,
      );
    } on DioException catch (e) {
      throw _map(e);
    }
  }

  Future<void> logout() async {
    try {
      await _dio.post('/auth/logout');
    } on DioException {
      // Ignore logout errors — clear local state regardless
    }
  }

  AppException _map(DioException e) {
    if (e.error is AppException) {
      return e.error as AppException;
    }
    final status = e.response?.statusCode;
    // Use the server's error message if present (e.g. "Invalid credentials" on 401).
    // Only fall back to AuthException when there is no body — that means it was a
    // token-expiry 401 generated by the interceptor with no response body.
    final body = e.response?.data;
    final msg = body is Map ? body['error'] as String? : null;
    if (msg != null) return ApiException(status ?? 0, msg);
    if (status == 401) return const AuthException();
    return ApiException(status ?? 0, 'Unknown error');
  }
}
